[package]
name = "undeath"
version = "0.1.0"
edition = "2021"

# Using <https://github.com/mstange/samply>.

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
rayon = "1.10.0"
